
<?php

$lang=array(

"wiz1" => "RÉPUBLIC ALGÉRIENNE DÉMOCRATIQUE ET POPULAIRE",	
"wiz2" => "MINISTÉRE DE L’ÉDUCATION NATIONALE",	
"cont" => "Contact",
"pres" => "Présentation de l'école",
"ens" => "Enseignements",
"acc" => "Accueil",
"rec" => "Recherche",
"pre" => "BELAID BELKACEM école Primaire & Maternelle",
"mn" => "Menu",
"ea" => "Espace administration",
"ee" => "Espace enseignants",
"ep" => "Espace parent d'eléve",
"mtdr" => "Mot de directeur de l'école",
"mtdr2" => "Louange à Dieu, par la grâce duquel les bonnes actions sont accomplies et par sa grâce les bénédictions et les prières du Prophète Muhammad, qui est décrit avec les meilleurs attributs, et sa famille et ses compagnons sont tous réalisés. Nous croyons aux futurs préparatifs pour les activités éducatives et nous nous concentrons sur l'éducation au stade de développement du primaire en prévision d'un avenir radieux.",
"act" => "Actualités",
"acta" => "Le héro BELAID BELKACEM",
"acta1" => "Décourvrer plus ce héro",
"acta2" => "Symbole de sacrifice",
"actb" => "Journée de savoir",
"actb1" => "Le 16 avril de chaque année",
"actb2" => "Commimoration",
"actc" => "Jour nationale de l'arbre",
"actc1" => "Le 25 octobre de chaque année",
"actd1"	=> "Annulation de l'examen du certificat d'études primaires",
"actd2"	=> "Calcul de la moyenne annuelle pour passer la première année moyenne",
"acte1" => "Les examens de troisieme trimestre",
"acte2" => "date de départ: 22/05/2022",
"actf1" =>	"BELAID BELKACEM© 2021-2022",
"pre1"	=>    "Présentation de l'école",
"ll" =>  	"L’école BLAIDE BELKACEM  est nommée par rapport le martyr de la révolution. Située dans le quartier BLAIDE BELKACEM  cité Juanola, Fakharine, ANNABA 23000. L’école BLAIDE BELKACEM accueille près de 663 élèves (2021-2022) de la maternelle à la cinquième année. 
L'établissement est sous un système demi-pensionnaire et externe, pour offrir de bonnes conditions d'études et de travail, accueillantes et fonctionnelles, qui sont réunies pour répondre aux enjeux de demain et aux besoins de formation des élèves.
",


"oo" => "1.	Locaux :",
"pp" =>"L’architecture de BLAIDE BELKACEM permet d’offrir des services adaptés aux besoins des enfants. Elle offre aux élèves des salles d'études, un espace de restauration,   salle de réunion, salle de soins,  une salle des enseignants, une cour, des toilettes, et un espace vert.",

"ss"   =>"Locaux",
"tt"   =>"Nombre de locaux",
"uu" =>"espace de restauration",	
"vv"   =>"Salles d'études",
"ww"   =>"Salle de réunion",
"xx" =>"Salle de soins",
"yy" =>"Salle des enseignants",
"zz" =>"cycle de l'eau",
"aa" =>"Cour",
"bb" =>"Espace vert",
"cc" =>"2.	Les élèves  :",
"dd" =>"Les statistiques montre que la primaire accueille 663 élèves, se subdivise sur tous les niveaux",
"ff" =>"Niveaux",
"gg" =>"Nombre des garçons",
"hh" =>"Nombre des filles",
"ii" =>"Maternelle",
"jj" =>"1ére année",
"kk" =>" 2éme année",
"LL" =>"3éme année ",
"MM" =>"4éme année ",
"NN" =>"5éme année ",
"OO" =>"Nombre de classe",
"PP" =>"3.	Les enseignants   :",
"QQ" =>	"BLAIDE BELKACEM est une école active et énergique, et ce, grâce à une communauté éducative et un bonne équipe d’enseignants qui assume la responsabilité d’assuré une bonne éducation. Le primaire regroupe 20 enseignants.",
"RR" =>	"Matière",
"SS" =>	"Nombre d'enseignants",
"TT" =>"Tout les matières",
"UU" =>	"Français",
"VV" =>	"4.	Les classes  :",
"dec" => "Déconnection",
"absds" =>"L'absence des enseignants",
"nom" => "Nom",
"clss" => "Classe",
"date" => "Date",
"envo" => "Envoyer",
"actua" => "Actualiser",
"sup" => "Supprimer",
"secon" => "Se connecter",
"entrvtn" => "Entrer votre nom",
"entrvrm" => "Entrer votre mot de passe",
"notel" => "Notes des éléves",
"ntfi" => "notifications",
"khamsa" => "5éme année",
"matier" => "Matiere",
"conten" => "Contenue",
"fich" => "Fichier",
"vosqst" => "VOS QUESTION",
"entrvte" => "Votre Email",
"vtrnmr" => "Votre numero télephone",
"cmntpt" => "Comment on peut vous aidez!",
"tania" => "2éme année",
"acces" => "Accés",
"arbre" => "La Journée nationale de l’arbre est une excellente opportunité de réfléchir à l’impact positif des arbres sur nos vies et de célébrer tous leurs bienfaits. Que ce soit en assainissant l’air, en régulant les eaux pluviales ou en stockant du CO2, les forêts urbaines jouent un rôle essentiel pour notre santé et notre bien-être. nous l’avoueons, nous sommes ni arboricultrice ni forestière, mais cela ne m’empêche pas de comprendre les bienfaits tangibles apportés par les arbres, y compris au niveau économique. nous pouvons comprendre qu’un arbre augmente la valeur d’une propriété et que des touristes affluent vers des endroits . alors l'école BELAID BEKCACEM célébre ce jour le 25 ocrobre de chaque anné.",
"joursvr" => "L'école BELAID BELKACEM a célébré la journée du SAVOIR (16 Avril ) يوم العلم , au sein de son établissement scolaire. Au programme, Les élèves du primaire ont chanté différentes chansons du répertoire national et international, classique, moderne et traditionnel. Quelques pièces théâtrales ont également été présentées et un concours interclasse.",
"hrblbl1" => "Le héros Belaid Belkacem, l'un des héros de la révolution de libération bénie dans la ville d'Annaba, a été martyrisé dans la région de la vallée du Nil le 24/01/1957, accompagné de dix-sept moudjahidines, après une bataille acharnée avec les forces d'occupation françaises. Il commence ses études secondaires à Constantine et effectue le service militaire français en 1940 de force et s'enfuit et est transféré au tribunal militaire en l'an 47 avant d'être libéré. Il a déménagé à Annaba, où il a travaillé au Centre de Formation Professionnelle et à la municipalité d'Annaba, jusqu'à ce qu'il rejoigne le travail de lutte au sein du Parti populaire algérien, qui s'est transformé en mouvement pour la victoire des libertés démocratiques et la découverte de son ordre par l'ennemi français Son ascension à Boukantas et son entrée dans les rangs de l'Armée de Libération à Serayede et Shatabi. Ce fut aussi l'occasion de raconter l'héroïsme de la célèbre Bataille de Boukantas en présentant un poème révolutionnaire du martyr Belaid Belkacem.",
"hrblbl2" => "Que Dieu ait pitié des martyrs, gloire et éternité à nos justes martyrs",
"clas1" => "Classe 1",
"clas2" => "Classe 2",
"noepr" => "Nom et prenom",
"arab" => "Arabe",
"matma" => "Mathematique",
"etdi" => "Etude islamique",
"etdci" => "Etude civile",
"etdcien" => "Etude scientifique",
"histegeo" => "Historique et geographique",
"frnci" => "Francais",
"moyn" => "Moyenne",
"trimstr" => "Trimestre",
"reslt" => "Resultat",
"elvvv" => "Les eLéves",
"ensss" => "Les enseignants",
"clsss" => "Les classes",
);

?>